apiVersion: v2
name: grafana
description: Grafana
type: application
version: 6.21.2
appVersion: 8.3.4
dependencies:
  - name: grafana
    version: 6.21.2
    repository: https://grafana.github.io/helm-charts
