---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: &app test-app
  labels:
    service: *app
spec:
  selector:
    app: *app
  ports:
  - name: web
    port: 8080
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: &app test-app-np
#  labels:
#    service: *app
#spec:
#  type: NodePort
#  selector:
#    app: test-app
#  ports:
#  - name: web
#    port: 8080
#    nodePort: 32005
