global:
  defaultStorageClass: "managed-nfs-storage"
  storageClass: "managed-nfs-storage"
# initial admin password
adminPassword: "password"
externalURL: https://harbor.kryukov.lan
logLevel: debug
ipFamily:
  ipv6:
    enabled: false
exposureType: proxy
nginx:
  tls:
    enabled: false
service:
  type: ClusterIP
  ports:
    http: 80
    https: 443
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    jobservice:
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    trivy:
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  imageChartStorage:
    type: filesystem
volumePermissions:
  enabled: true
portal:
  networkPolicy:
    enabled: false
core:
  networkPolicy:
    enabled: false
jobservice:
  networkPolicy:
    enabled: false
registry:
  networkPolicy:
    enabled: false
trivy:
  networkPolicy:
    enabled: false
exporter:
  networkPolicy:
    enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: postgresql.pg.svc
  port: 5432
  user: artur
  password: "password"
  sslmode: disable
  coreDatabase: "harbor"
redis:
  enabled: false
externalRedis:
  host: redis-master.redis.svc
  port: 6379
  password: "qUwTt8g9it"
  coreDatabaseIndex: "0"
  jobserviceDatabaseIndex: "1"
  registryDatabaseIndex: "2"
  trivyAdapterDatabaseIndex: "5"

